---
title: "Day 4 - Comp session"
format: html
editor: visual
---

```{r}
quarter_splits <- c(1.0, 1.1, 1.2, 1.1, 1.4, 1.5, 1.6, 1.4)

for (i in seq_along(quarter_splits)) {
  half_time <- quarter_splits[i] + quarter_splits[i + 1]
  print(half_time)
}
```

## Intro to functions

Make a function to double the user input.

```{r}
double_this <- function (my_value) {
  print(2 * my_value)
}

double_this(my_value = 200)
double_this(200)

double_this(c(1, 2, 10, 100, 175))
```

Your turn: Write a function that asks for a user's name and age and returns an exclamation, like "I'm [name], and I am [age] years old."

```{r}
exclaim_name_and_age <- function(name, age) {
  print(paste("I'm", paste0(name, ","), "and I am", age, "years old!"))
}

exclaim_name_and_age("Erika", 22)
```

```{r}
convert_animal_age <- function(animal, age) {
  if (animal == "dog") {
    print(age * 7)
  } else if (animal == "goat") {
    print(age * 4.7)
  } else {
    stop("Not a valid animal choice")
  }
}

convert_animal_age(animal = "dog", age = 8)
convert_animal_age(animal = "goat", age = 8)
convert_animal_age(animal = "parrot", age = 8)
```

```{r}
dog_choice <- tribble(
  ~dog_name, ~food,
  "Khora", "everything",
  "Teddy", "salmon",
  "Waffle", "pancakes",
  "Banjo", "chicken"
)

dog_menu <- function(name) {
  my_sub <- filter(dog_choice, dog_name == name)
  print(paste("My name is", my_sub$dog_name, "and my favorite food is", my_sub$food))
}

dog_menu("Waffle")
```

## Functions meet for loops

```{r}
means_over_columns <- function(df) {
  for (i in seq_along(df)) {
    col_mean <- mean(df[[i]], na.rm = TRUE)
    column_name <- colnames(df[i])
    print(paste("The mean value of", column_name, "is", col_mean))
  }
}

means_over_columns(df = mtcars)

means_over_columns(df = faithful)
```

